# Updated by Wen Han Tang A0340008W
# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_cfac0af099f438601b15da31d814215ac81b294f

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sourceEncoding=UTF-8
sonar.sources=controllers,middlewares,helpers,routes,models,config,client/src
sonar.tests=integration,tests,controllers,middlewares,helpers,client/src
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.exclusions=**/node_modules/**,**/coverage/**,**/playwright-report/**,**/test-results/**,client/src/_site/**,client/public/**
sonar.coverage.exclusions=**/*.test.js,**/*.spec.js,tests/**,integration/**,client/src/_site/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
